server:
  port: 7001   #服务端端口

eureka:
  instance:
    hostname: localhost      #主机名称  192.168.9.52
  client:
    registerWithEureka: false   #eureka服务器不需要自己给自己注册
    fetchRegistry: false
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

