server:
  port: 7005

eureka:
  client:
    service-url:
      defaultZone: http://yumbo.top:7001/eureka/   #要连接的注册中心（eureka服务器）地址
#  instance:
#    prefer-ip-address: true #显示ip
#    instance-id: server-provider
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: USER-SERVICE-PROVIDER
  datasource:   #数据源
    url: jdbc:mysql://yumbo.top:3306/sunusedcar?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8   #配置数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123456.
    #数据连接池   使用要求必须是数据源也是从配置文件中读取的，否则不生效
    tomcat:
      max-wait: 10000
      max-active: 100
      max-idle: 50
      min-idle: 10

#添加mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.yumbo.springcloud.car.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#ribbon:
#  eureka:
#    enabled: true