server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://yumbo.top:7001/eureka/   #要连接的注册中心（eureka服务器）地址
spring:
  application:
    name: CAR-MANAGE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yumbo.top:3306/sunusedcar?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: abc123456.
    #数据连接池   使用要求必须是数据源也是从配置文件中读取的，否则不生效
    tomcat:
      max-wait: 10000
      max-active: 100
      max-idle: 50
      min-idle: 10


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
